project:
  type: website
  render:
    - "index.qmd"
    - "docs/"
    - "!notebooks/"
    - "!docs/source/"
    - "!docs/build/"
    - "!*.ipynb"
    - "!docs/gtfs/*"
  preview:
    port: 1111
    browser: true
    watch-inputs: true
    navigate: true
  resources:
    - "docs/_static/**"

website:
  title: "Transport Performance"
  favicon: docs/_static/favicon.ico
  navbar:
    logo: docs/_static/tp_logo_white_background.png
    left:
      - href: docs/getting_started.qmd
        text: Getting Started
      - href: docs/explanation/index.qmd
        text: Explanation
      - href: docs/tutorials/index.qmd
        text: Tutorials
      - href: docs/reference/index.qmd
        text: API Reference
    right:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/datasciencecampus/transport-network-performance
          - text: Open an issue
            url: https://github.com/datasciencecampus/transport-network-performance/issues
  sidebar:
    style: docked
    search: true
    collapse-level: 1
    contents:
      - text: Getting Started
        href: docs/getting_started.qmd
      - section: Explanation
        href: docs/explanation/index.qmd
        contents:
          - "docs/explanation/what_is_tp/index.qmd"
          - "docs/explanation/calculate_tp/index.qmd"
          - "docs/explanation/limitations/index.qmd"
      - section: Tutorials
        href: docs/tutorials/index.qmd
        contents:
          - auto: "docs/tutorials/*.qmd"
      - section: API Reference
        href: docs/reference/index.qmd
        contents:
          - auto: "docs/reference/*.qmd"
  reader-mode: true
  page-footer:
    left: >
      These docs are built using [Quarto](https://quarto.org/) and [quartodoc](https://machow.github.io/quartodoc/get-started/overview.html).
    center: >
      All content is available under the
      [Open Government Licence V3.0](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/),
      except where otherwise stated.
    right: >
      <a href="https://datasciencecampus.ons.gov.uk/">
        <img src="https://datasciencecampus.ons.gov.uk/wp-content/uploads/sites/10/2019/05/DSC.png" alt="Data Science Campus logo" style="height:25px;">
      </a>

format:
  html:
    mainfont: Arial
    theme:
      - flatly
      - docs/_static/custom.scss
    lang: en-GB

metadata-files:
  - docs/_sidebar.yml

quartodoc:
  title: API reference
  package: transport_performance
  dir: docs/reference
  sidebar: docs/_sidebar.yml
  sections:
    - title: gtfs
      desc: >
        Tools for working with GTFS files.
      package: transport_performance.gtfs
      contents:
        - calendar
        - cleaners
        # - gtfs_utils
        # - multi_validation
        - routes
        # - validation
        - validators
    - title: population
      desc: Population tools.
      package: transport_performance.population
      contents:
       # - rasterpop
        - vectorpop
    - title: utils
      desc: Utilities
      package: transport_performance.utils
      contents:
        - constants
        - defence
        - io
        # - raster
        - test_utils
