---
title: "`transport_performance` documentation"
title-block-banner: true
date-format: iso
description: |

  A Python package bringing together open-source data, tools, and research to
  make transport network analyses more simple, reproducible, and consistent for
  everyone.
toc: true
toc-title: "On this homepage"
sidebar: false
about:
    template: marquee
    links:
        - icon: github
          href: https://github.com/datasciencecampus/transport-network-performance
          text: GitHub
---

## What is `transport_performance`?

The performance of transport networks are highly variable throughout and
between countries. There is often a lack of consistent and comparable data
which can make it difficult to understand these differences. This is typically
because of computational complexity, transparency (closed-source and paid
services), and data consistency (format and availability).

To start resolving these issues, the `transport_performance` Python package
bringing togethers a range of open source tools and research to allow everyone
to:

- Define an [urban centre] boundary based on population density;
- Inspect, clean, and process [public transit timetable data][gtfs] and
[OpenStreetMap data][osm]; and
- Conduct [multimodal routing][r5py] and calculate a range of
[transport metrics][eurostat-paper].

::: {.callout-tip}

Check out the corresponding [Docker image][tp-docker] 🐳!
This aims to simplify both the dependency installation and end-to-end use of
`transport_performance`.

:::

## Where do I go now?

These docs are structured in accordance with the [Diátaxis][diataxis] framework:

<div class="grid-container">
<div class="grid-item item1 jumbotron">
<p class="jumbotron-icon">🏁</p>
<p>Want to get up and running with `transport_performance` quickly?</p>
<a class="btn btn-primary btn-lg" href="./docs/getting_started/" role="button">Getting Started</a>
</div>
<div class="grid-item item2 jumbotron">
<p class="jumbotron-icon">🔎</p>
<p>Need more details on the methods/tools used within `transport_performance`?</p>
<a class="btn btn-primary btn-lg" href="./docs/explanation" role="button">Explanation</a>
</div>
<div class="grid-item item3 jumbotron">
<p class="jumbotron-icon">🧭</p>
<p>Looking for guidance on how to get something done (e.g. find input data)?</p>
<a class="btn btn-primary btn-lg" href="./docs/how_to" role="button">How-To</a>
</div>
<div class="grid-item item4 jumbotron">
<p class="jumbotron-icon">📝</p>
<p>Interested in learning how to use `transport_performance` by examples?</p>
<a class="btn btn-primary btn-lg" href="./docs/tutorials" role="button">Tutorials</a>
</div>
<div class="grid-item item5 jumbotron">
<p class="jumbotron-icon">📖</p>
<p>Requiring a technical reference covering the `transport_performance` API?</p>
<a class="btn btn-primary btn-lg" href="./docs/reference" role="button">API reference</a>
</div>
<div class="grid-item item6 jumbotron">
<p class="jumbotron-icon">🛠️</p>
<p>Want to contribute to the development of `transport_performance`?</p>
<a class="btn btn-primary btn-lg" href="https://github.com/datasciencecampus/transport-network-performance" role="button">GitHub</a>
</div>
</div>

::: {.callout-note}

## Notes on contributing...

We hope that the public, other public sector organisations, and other National
Statistical Institutes can collaborate and build on this package. This will
help improve both the national and international comparability of transport
statistics whilst enabling higher frequency and more timely comparisons. You can
find the `transport_performance` source code on [GitHub](https://github.com/datasciencecampus/transport-network-performance).

:::


[diataxis]: https://diataxis.fr/
[tp-docker]: https://github.com/datasciencecampus/transport-performance-docker
[urban centre]: https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Urban_centre
[gtfs]: https://gtfs.org/schedule/
[osm]: https://wiki.openstreetmap.org/wiki/Main_Page
[r5py]: https://r5py.readthedocs.io/en/stable/index.html
[eurostat-paper]: https://ec.europa.eu/regional_policy/information-sources/publications/working-papers/2020/low-carbon-urban-accessibility_en
