[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0.0", "wheel"]

[project]
name = "transport_performance"
authors = [
    {name = "Data Science Campus", email = "datasciencecampus@ons.gov.uk"}
]
description = "Measuring the performance of transport networks around urban centres"
readme = "README.md"
classifiers = [
    "Development Status :: 1 - Planning",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Topic :: Scientific/Engineering :: GIS",
]
requires-python = ">=3.9"
version = "0.0.1"

dependencies = [
    'assess-gtfs',
    'cartopy',
    'dask[dataframe]',
    'folium',
    'geocube',
    'geopandas',
    'haversine',
    'osmium',
    'pandas<2.1.0',
    'pyarrow>=14.0.1', # 14.0.0 has security vulnerability
    'pyproj>=3.6.0',
    'pyprojroot',
    'rioxarray',
    'mapclassify',
    'matplotlib>=3.7.0',
    'r5py==0.1.0',
    'rasterio',
    'scipy',
    'numpy==1.26.4',
    'tqdm',
    'xyzservices',
]

[project.optional-dependencies]
test = [
    'pytest<8.0.0',
    'pytest-mock',
    'pytest-lazy-fixture',
]

dev = [
    'build',
    'coverage',
    'pre-commit',
]

docs = [
    'ipykernel==6.23.1',
    'jupyterlab',
    'nbformat>=4.2.0',
    'quartodoc',
    'requests',
    'seaborn',
    'toml',
]

[tool.setuptools]
# This is true by default so this can be removed.
# Currently retaining this line before discussing with others whether or not
# we want to keep it for more clarity.
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Repository = "https://github.com/datasciencecampus/transport-network-performance"
"Bug tracker" = "https://github.com/datasciencecampus/transport-network-performance/issues"

# `coverage` configurations
[tool.coverage.run]
source = [
    "./src"
]
omit = ["**/__init__.py"]

[tool.coverage.report]
exclude_lines = [
    "if __name__ == .__main__.:"
]

# `isort` configurations
[tool.isort]
profile = "black"
skip_glob = ["notebooks/*"]
line_length = 79

# `pytest` configurations
[tool.pytest.ini_options]
addopts = [
    "-vv",
    "--doctest-modules"
]
doctest_optionflags = "NORMALIZE_WHITESPACE"
testpaths = [
    "./tests"
]
