title = "Config for GTFS Validation Pipeline"

[GTFS]
PATH = "data/external/croppednewport-bus-07-07-2022_gtfs.zip"
UNITS = "m"
GEOMETRIC_CRS = 27700 # used for area calculations only

[MAPS]
STOP_COORD_PTH = "outputs/gtfs/validation/gtfs-stops-locations.html"
STOP_HULL_PTH = "outputs/gtfs/validation/gtfs-stops-convex_hull.html"

[UTILS]
PROFILING = true
