title = "Config for GTFS Validation Pipeline"

[GTFS]
PATH = "tests/data/gtfs/newport-20230613_gtfs.zip"
UNITS = "m"
GEOMETRIC_CRS = 27700 # used for area calculations only

[MAPS]
STOP_COORD_PTH = "outputs/gtfs/validation/gtfs-stops-locations.html"
STOP_HULL_PTH = "outputs/gtfs/validation/gtfs-stops-convex-hull.html"

[UTILS]
PROFILING = true
