---
-title: "4. OpenStreetMap (OSM)"
-description: Learn how to use the `transport_performance.osm` module through examples.
-date-modified: 06/05/2024  # must be in MM/DD/YYYY format
categories: ["Tutorial"]  # see https://diataxis.fr/tutorials-how-to/#tutorials-how-to, delete as appropriate
toc: true
date-format: iso
jupyter: transport-performance
---

## Introduction

### Outcomes

[OpenStreetMap](https://welcome.openstreetmap.org/what-is-openstreetmap/#:~:text=OpenStreetMap%20is%20a%20free%2C%20editable,that%20was%20free%20to%20use.)
(OSM) is a free, community-maintained source of spatial information. It
contains information about the properties of street networks and has
international coverage. We use these data in combination with General Transit
Feed Specification data to build public transit networks for routing
operations.

In this tutorial we will learn how to prepare OSM data for routing.
Specifically, we will:

* Download OSM data.
* Filter the osm files to an area of interest with a bounding box.
* Examine features of the transit network.

### Requirements

To complete this tutorial, you will need:

* python 3.9
* Stable internet connection
* Installed the `transport_performance` package (see the
[getting started explanation](/docs/getting_started/index.qmd) for help)

:::{.callout-important}

## Requirements

`transport_performance.osm` is built on
[`osmosis`](https://wiki.openstreetmap.org/wiki/Osmosis/Installation) and is
tested on macos and linux only.
:::

## Downloading OSM

Let's import the necessary dependencies:

```{python}
import subprocess

from pyprojroot import here

from transport_performance.osm.osm_utils import filter_osm
from transport_performance.osm import validate_osm

```

We require a source of OSM data in
[Protocolbuffer Binary Format (PBF)](https://wiki.openstreetmap.org/wiki/PBF_Format).
We recommend sourcing exerpts of this data hosted on
[Geofabrik's Download Server](https://www.geofabrik.de/data/download.html).
This server is provided free of charge by Geofabrik and can come under
considerable demand at certain times of the day. Please use this service
considerately.

:::{.panel-tabset}

### Task

Navigate the Geofabrik Download Server and download OSM data for an area of
interest. Save the data and instantiate a path to the file called
`original_osm_path`.

### Hint

```{python}
#| eval: false
original_osm_path = <INSERT_PATH_HERE>

```

### Solution

```{python}
original_osm_path = here("tests/data/newport-2023-06-13.osm.pbf")
```

:::

## Define the Area of Interest

:::{.panel-tabset}

Using a service such as [Klokantech](), define a bounding box within the territory of the OSM file that you downloaded.

### Task

Extract the bounding box in comma separated value format. Assign to a list in xmin, ymin, xmax, ymax format. Call the list `BBOX_LIST`.

### Hint

```{python}
#| eval: false
BBOX_LIST = [<INSERT_VALUES_HERE>]
```

### Exercise

```{python}
BBOX_LIST = [-3.002175, 51.587035, -2.994271, 51.59095]
```

:::

## Filtering PBF

As PBF files can be very large and contain lots of data that are irrelevant to our routing purposes, we can filter the data to the road network. Ensure that you have `osmosis` installed for this task.

:::{.panel-tabset}

### Task

Define a `filtered_osm_path` object to save the filtered pbf file to.

Use the `filter_osm()` function to restrict the PBF file to the extent of `BBOX_LIST`. Inspect `help(filter_osm)` for information on all available parameters.

### Hint

```{python}
#| eval: false
filtered_osm_path = <INSERT_A_PATH>
filter_osm(pbf_pth=original_osm_path, out_pth=filtered_osm_path, bbox=BBOX_LIST)

```

### Solution

```{python}
filtered_osm_path = here("foo.pbf")
filter_osm(
    pbf_pth=original_osm_path, out_pth=filtered_osm_path, bbox=BBOX_LIST)

```

:::

Notice that `osmosis` is quite chatty and will often print various exceptions originating from the Java code. If the filter operation was performed successfully, you should see `INFO: Pipeline complete.` and an execution time printed to the console.

Now that we have performed the filter, we should notice a significant change in the size of the file on disk.

```{python}
orig_du = subprocess.run(["du", "-sh", original_osm_path], text=True, capture_output=True).stdout.split("\t")[0]
orig_du
filtered_du = subprocess.run(["du", "-sh", filtered_osm_path], text=True, capture_output=True).stdout.split("\t")[0]
print(f"After filtering, PBF size reduced from {orig_du} to {filtered_du}")

```

## Count OSM Features

From this point on in the tutorial, it is suggested to work with a small, filtered PBF file as the computations can be slow.

PBF data contain spatial data organised with [tagged (labelled) elements](https://wiki.openstreetmap.org/wiki/Elements). We can access these elements to explore the features stored within the file.

The first step in understanding the contents of your PBF file is to explore the tag IDs that are available.

:::{.panel-tabset}

### Task

Use the `validate_osm.FindIds` class to discover the full list of IDs within the pbf file saved at `filtered_osm_path`. Assign the class instance to `id_finder`.

Use an appropriately named method to count the available IDs within the file.

### Hint

```{python}
#| eval: false
id_finder = validate_osm.<INSERT_CLASS_NAME>(osm_pth=filtered_osm_path)
id_finder.<INSERT_METHOD_NAME>()

```

### Solution

```{python}
id_finder = validate_osm.FindIds(osm_pth=filtered_osm_path)
id_finder.count_features()

```

:::

You should find that there are four classes of IDs within the returned dictionary:

* Nodes
* Ways
* Relations
* Areas

For our purposes we can focus on nodes and ways. Nodes will be point locations on the travel network such as junctions or bends in the road whereas ways are collections of nodes forming a road or section of road.

If we have IDs for nodes or ways, we can visualise their locations on a map. To do this, we first need a list of IDs.

## Return IDs for a Way

:::{.panel-tabset}

### Task

Using the `id_finder` instance we instantiated earlier, find all of the IDs labelled as ways in the PBF file. Assign these IDs to a list called `way_ids`. Print the first 10 IDs.

### Hint

```{python}
#| eval: false
way_ids = id_finder.<INSERT_METHOD>()["<INSERT_CORRECT_KEY>"]
way_ids[0:10]
```

### Solution

```{python}
way_ids = id_finder.get_feature_ids()["way_ids"]
way_ids[0:10]
```

:::

## Retrieve Coordinate Data

Armed with these IDs, we can now locate the features within the PBF file and visualise them against a base map.

:::{.panel-tabset}
### Task

Assign `validate_osm.FindLocation` to an instance called `loc_finder`. You will need to point this class to the same filtered PBF file as you used previously.

Using the `check_locs_for_ids()` method, pass a list of ten IDs from the `way_ids` list you created in the previous exercise. Assign the extracted coordinates to `way_coords` and print the first **ID** (the IDs you passed to `check_locs_for_ids()` will be keys in the returned dictionary).

### Hint

```{python}
#| eval: false
loc_finder = validate_osm.<INSERT_CLASS>(osm_pth=filtered_osm_path)
way_coords = loc_finder.<INSERT_METHOD>(way_ids[0:10], feature_type="<INSERT_FEATURE_TYPE>")
way_coords[<INSERT_AN_ID_VALUE>]
```

### Solution


```{python}
loc_finder = validate_osm.FindLocations(osm_pth=filtered_osm_path)
way_coords = loc_finder.check_locs_for_ids(way_ids[0:10], feature_type="way")
way_coords[2954415]
```

:::

You should notice that this way feature contains multiple nodes with coordinate data.

## Visualising OSM Features

Now that we have returned the coordinate data for the way, it is straight forward to visualise the points on a map.

:::{.panel-tabset}

### Task

Using the `way_ids` list from a previous task, pass the first three IDs to `loc_finder.plot_ids()` in a list. Ensure that you specify that the `feature_type` is `"way"`.

### Hint

```{python}
#| eval: false
loc_finder.<INSERT_METHOD>(ids=way_ids[<START>:<END>], feature_type="<INSERT_FEATURE_TYPE>")
```

### Solution

```{python}
loc_finder.plot_ids(ids=way_ids[0:3], feature_type="way")
```

:::


## Conclusion

Congratulations, ...

To continue learning how to work with the `transport_performance` package, it
is suggested that you continue with the
[...](/...)

For any problems encountered with this tutorial or the `transport_performance`
package, please open an issue on our
[GitHub repository](https://github.com/datasciencecampus/transport-network-performance/issues).
