---
title: Filtering GTFS Feeds
description: A tutorial quality assuring General Transit Feed Specification.
format: html
toc: true
jupyter:
  kernelspec:
    name: "conda-env-transport-performance-py"
    language: "python"
    display_name: "transport-performance"
css: /www/styles.css
---

## Introduction

### Outcomes

This tutorial will takes the user through how to reduce the size of
[General Transit Feed Specification (GTFS)](https://gtfs.org/) feeds. This is
an important step when reducing the cost of routing operations.

While working towards this outcome, we will:

* Download open source GTFS data.
* Carry out some basic checks across the entire GTFS feed.
* Visualise the GTFS feed's stop locations on an interactive map.
* Filter the GTFS feed to a specific bounding box.
* Filter the GTFS feed to a specific date range.
* Check if our filter operations has resulted in an empty feed.
* Attempt to clean the feed.
* Reverse-engineer a calendar.txt if it is missing.
* Write the filtered feed to disk.

### Requirements

To complete this tutorial, you will need:

* python 3.9
* Stable internet connection
* Installed the `transport_performance` package (see the
[getting started explanation](/docs/getting_started/index.qmd) for help)
* The following requirements:

```{.abc filename=requirements.txt}
geopandas
pyprojroot
shapely
. # ensure transport_performance is installed

```

## Working With GTFS

Let's import the necessary dependencies:

```{python}
import datetime
import os
import subprocess
import tempfile

import geopandas as gpd
from pyprojroot import here
from shapely.geometry import Polygon

from transport_performance.gtfs.multi_validation import MultiGtfsInstance

```

We require a source of public transit schedule data in GTFS format. The French
government publish all of their data, along with may useful validation tools to
the website [transport.data.gouv.fr](https://transport.data.gouv.fr/datasets/).

:::{.panel-tabset}

### Task

Searching through this site for various regions and data types, you may be able
to find an example of GTFS for an area of interest. Make a note of the
transport modality of your GTFS, is it bus, rail or something else?

You may wish to manually download at least one GTFS feed and store somewhere in
your file system. Alternatively you may programmatically download the data, as
in the solution here.

### Hint

```{python}
#| eval: false
BUS_PTH = here("<INSERT_SOME_PATH_FOR_BUS_GTFS>")
RAIL_PTH = here("<INSERT_SOME_PATH_FOR_RAIL_GTFS>")
BUS_URL = "<INSERT_SOME_URL_TO_BUS_GTFS>"
RAIL_URL = "<INSERT_SOME_URL_TO_RAIL_GTFS>"
subprocess.run(["curl", BUS_URL, "-o", BUS_PTH])
subprocess.run(["curl", RAIL_URL, "-o", RAIL_PTH])

```

### Solution

```{python}
BUS_PTH = here("TMP_GTFS/bus_gtfs.zip")
RAIL_PTH = here("TMP_GTFS/rail_gtfs.zip")
BUS_URL = "https://app.mecatran.com/utw/ws/gtfsfeed/static/mamp-cio?apiKey=2b37114236244f1e115f6542331d243617772448"
RAIL_URL = "https://eu.ftp.opendatasoft.com/sncf/gtfs/export-intercites-gtfs-last.zip"

if not os.path.exists(BUS_PTH):
    # tmp_path = tempfile.TemporaryDirectory()
    # bus_path = os.path.join(tmp_path.name, "provence_ciotabus_gtfs.zip")
    # rail_path = os.path.join(tmp_path.name, "intercity_rail_gtfs.zip")
    # subprocess.run(["curl", BUS_URL, "-o", bus_path])
    # subprocess.run(["curl", RAIL_URL, "-o", rail_path])
    # assert os.path.exists(gtfs_path)
    # assert os.path.exists(rail_path)
    subprocess.run(["curl", BUS_URL, "-o", BUS_PTH])
    subprocess.run(["curl", RAIL_URL, "-o", RAIL_PTH])
else:
    pass

```

:::

***

Now that we have ingested the GTFS feed(s), you may wish to open the files up
on your file system and inspect the contents. GTFS feeds come in compressed
formats and contain multiple text files. These files can be read together, a
bit like a relational database, to produce a feed object that is useful when
undertaking routing with public transport modalities.

To do this, we will need to use a class from the `transport_performance`
package called `MultiGtfsInstance`. Let's take a look at the class docstring to
help us understand how it works.

:::{.scrolling}

```{python}
help(MultiGtfsInstance)
```

:::

***

`MultiGtfsInstance`; as the name sounds; can cope with multiple GTFS feeds at a
time. If you have chosen to download several feeds, then point the `path`
parameter at a directory that contains all of the feeds. If you have chosen to
download a single feed, then you may pass the full path to the feed.

:::{.panel-tabset}

### Task

Instantiate a `feed` object by pointing the `MultiGtfsInstance` class at a path
to the GTFS feed(s) that you have downloaded. Once you have successfully
instantiated `feed`, inspect the correct attribute in order to confirm the
number of separate feeds instances contained within it.

### Hint

```{python}
#| eval: false
gtfs_pth = "<INSERT_PATH_TO_GTFS>"
feed = MultiGtfsInstance(path=gtfs_pth)
print(len(feed.<INSERT_CORRECT_ATTRIBUTE>))

```

### Solution

```{python}
gtfs_pth = here("TMP_GTFS/")
try:
    feed = MultiGtfsInstance(path=gtfs_pth)
except ValueError:
    raise ValueError(f"location of here is: {gtfs_pth}")
except FileNotFoundError:
    raise FileNotFoundError(f"location of here is: {os.listdir(gtfs_pth)}")
print(f"There are {len(feed.instances)} feed instances")

```

:::

Each individual feed can be accessed seperately. Their contents should confirm
their file contents on disk.

:::{.scrolling}

```{python}
help(feed.instances[0].feed)

```

:::

:::{.panel-tabset}

### Task

By accessing the appropriate attribute, print out the first 5 stops of the
first instance within the `feed` object.

### Hint

```{python}
#| eval: false
feed.<INSERT_CORRECT_ATTR>[0].feed.stops.<INSERT_CORRECT_METHOD>(5)
```

These records will match the contents of the stops.txt file within the feed
that you downloaded.

***

### Solution

```{python}
feed.instances[0].feed.stops.head(5)
```

:::

## Checking Validity

Transport routing operations require services that run upon a specified date.
It is a useful sanity check to confirm that the dates that you expect to
perform routing on exist within the GTFS feed. To do this, we can use the
`get_dates()` method to print out the first and last date in the available date
range, as below.

```{python}
s0, e0 = feed.get_dates()
print(f"Feed starts at: {s0}\nFeed ends at: {e0}")
```

:::{.panel-tabset}

### Task

How can we have this method print out the full list of dates available within
the feed?

### Hint

Examine the `MultiGtfsInstance` docstring printed earlier and find the name of
the parameter that controls the behaviour of `get_dates()`.

### Solution

:::{.scrolling}

```{python}
feed.get_dates(return_range=False)

```

:::

:::

Openly published GTFS feeds from a variety of different providers have varying
degrees of quality and not all feeds strictly adhere to the defined
specification for this type of data. When working with new sources of GTFS, it
is advisable to investigate the types of errors or warnings associated with
your particular feed(s).

:::{.panel-tabset}

### Task

Check if the feed you've instantiated contains valid GTFS.

### Hint

Check the docstring we printed earlier for an appropriate method. Depending
upon the source of the GTFS, you may need to ensure that checking of fast
travel is switched off. To turn off fast travel checks, pass the following
dictionary to the method's appropriate argument: `{"far_stops": False}`

### Solution

:::{.scrolling}

```{python}
feed.is_valid(validation_kwargs={"far_stops": False})
```

:::

:::

Note that it is common to come across multiple warnings when workign with GTFS.
Many providers include additional columns that are not part of the GTFS. This
typically poses no problem when using the feed for routing operations.

In certain feeds, you may notice errors flagged due to unrecognised route
types. This is because certain providers publish feeds that conform to
[Google's proposed GTFS extension](https://developers.google.com/transit/gtfs/reference/extended-route-types).
Although flagged as an error, valid codes associated with the proposed
extension typically do not cause problems with routing operations.

## Viz Stops

A sensible check when working with GTFS for an area of interest, is to
visualise the stop locations of your feed.

:::{.panel-tabset}

### Task

By accessing an appropriate method for your feed, plot the stop locations on an
interactive folium map.

### Hint

Inspect the `MultiGtfsInstance` docstring for the appropriate method.

```{python}
#| eval: false
feed.viz_...()
```

### Solution

```{python}
feed.viz_stops()
```

:::

By inspecting the location of the stops, you can visually assess that they
concur with the road network depicted on the folium basemap.

## Filtering GTFS

Cropping GTFS feeds can help optimise routing procedures. GTFS feeds can often
be much larger than needed for smaller, more constrained routing operations.
Holding an entire GTFS in memory may be unnecessary and burdensome. In this
section, we will crop our feeds in two ways:

* Spatially by restricting the feed to a specified bounding box.
* Temporally by providing a date (or list of dates).

Before undertaking the filter operations, examine the size of our feed on disk:

```{python}
out = subprocess.run(
    ["du", "-sh", here("TMP_GTFS")], capture_output=True, text=True)
size_out = out.stdout.strip().split("\t")[0]
print(f"Unfiltered feed is: {size_out}")
```

### By Bounding Box

To help understand the requirements for spatially cropping a feed, inspect the
docstring for the `filter_to_bbox()` method:

```{python}
help(feed.filter_to_bbox)
```

To perform this crop, we need to get a bounding box from a service such as
[klokantech](https://boundingbox.klokantech.com/) in csv format. It should be
in epsg:4326 projection (longitude & latitude).

Below I define a bounding box and visualise for context. Feel free to update
the code with your own bounding box values.

```{python}
BBOX = [4.932916,43.121441,5.644253,43.546931] # crop around Marseille
xmin, ymin, xmax, ymax = BBOX
poly = Polygon(((xmin,ymin), (xmin,ymax), (xmax,ymax), (xmax,ymin)))
poly_gdf = gpd.GeoDataFrame({"geometry": poly}, crs=4326, index=[0])
poly_gdf.explore()

```

:::{.panel-tabset}

#### Task

Crop your feed to the extent of your bounding box.

#### Hint

Pass the `BBOX` list in [xmin, ymin, xmax, ymax] order to the
`filter_to_bbox()` method.

#### Solution

```{python}
feed.filter_to_bbox(BBOX)
```

:::

Notice that a progress bar confirms the number of successful filter operations
performed depending on the number of seperate GTFS zip files passed to
`MultiGtfsInstance`.

Below I plot the filtered feed stop locations in relation to the bounding box
used to restrict the feed's extent.

```{python}
imap = feed.viz_stops()
poly_gdf.explore(m=imap)

```

Although there should be fewer stops observed, you will likely observe that
stops outside of the bounding box you provided remain in the filtered feed.
This is to be expected, particularly where GTFS feeds contain long-haul
schedules that intersect with the bounding box that you provided.

### By Date

```{python}
today = datetime.datetime.today().strftime(format="%Y%m%d")
feed.filter_to_date(today)
print(f"Filtered GTFS feed to {today}")
```

```{python}
s1, e1 = feed.get_dates()
print(f"After filtering to {today}\nstart date: {s1}\nend date: {e1}")
```


## Check Empty Feeds

```{python}
feed.validate_empty_feeds()

```

## Create Calendar

```{python}
for i, inst in enumerate(feed.instances):
    if inst.feed.calendar is None:
        problem_ind = i
print(f"Feed instance {i} has no calendar.txt")

```

```{python}
feed.ensure_populated_calendars()

```

```{python}
print("Newly populated calendar table:")
print(feed.instances[problem_ind].feed.calendar.head())

```

## Clean Feed

:::{.scrolling}

```{python}
feed.clean_feeds()
feed.is_valid(validation_kwargs={"far_stops": False})

```

:::

## Write Filtered Feed

Write new feed to disk

```{python}
filtered_pth = here("TMP_GTFS/filtered_feed")
try:
    os.mkdir(filtered_pth)
except FileExistsError:
    pass
feed.save_feeds(filtered_pth, overwrite=True)
```

Check filtered file size

```{python}
out = subprocess.run(
    ["du", "-sh", filtered_pth], capture_output=True, text=True)
filtered_size = out.stdout.strip().split("\t")[0]
print(f"After filtering, feed size reduced from {size_out} to {filtered_size}")
```
