title = "Config for an E2E example around the Newport area"

[urban_centre]  # configuration section for urban centre
override = true
input_dir = "data/external/urban_centre/"
merged_resampled_path = "data/processed/urban_centre/uc_merged_resampled.tif"

[population]  # configuration section for population
override = true
input_dir = "data/exteral/population/"
merged_resampled_path = "data/processed/population/pop_merged_resampled.tif"
