title = "Config for an E2E example around the Marseille area"

# `override` variable in the sections below can be used to skip over stages
# which take some time to execute. When running for the first time, it is
# necessary to set these variables to `true` so that the intermediate and
# processed data sources can be built. Afterwards, feel free to set these to
# `false` to avoid rebuilding 'expensive' processed inputs.
# Use the `write_outputs` flags below to control whether or not to write
# geneerated outputs to file (useful if you do not want to overwrite results).

[urban_centre]  # configuration section for urban centre
override = true
input_dir = "data/external/urban_centre/"
merged_path = "data/processed/urban_centre/uc_merged.tif"
bbox = [
    426000.0,
    5137000.0,
    465000.0,
    5176000.0
]  # must in in 'ESRI:54009'
centre = [445500.0, 5156500.0]
buffer_size = 12000
write_outputs = true
output_map_path = "outputs/e2e/marseille/urban_centre/urban_centre_map.html"

[population]  # configuration section for population
override = true
input_dir = "data/external/population/"
merged_path = "data/interim/population/pop_merged.tif"
merged_resampled_path = "data/processed/population/pop_merged_resampled.tif"
threshold = 1  # set small and positive, to remove 0 pop cells
write_outputs = true
output_map_path = "outputs/e2e/population/marseille/population_map.html"

[gtfs] # configuration section for gtfs
override = true
input_path = "data/external/gtfs/Gtfs_marseille_2023-10-24/*.zip"
filtered_path = "data/interim/gtfs/marseille/"
units = "km"
write_outputs = true
cleaned_path = "data/processed/gtfs/marseille/"
stops_map_path = "outputs/e2e/marseille/gtfs/stops_map"
hull_map_path = "outputs/e2e/marseille/gtfs/hull_map"
used_stops_map_path = "outputs/e2e/marseille/gtfs/used_stops_map"

[osm] # configuration section for osm clipping
override = true
input_path = "data/external/osm/provence-alpes-cote-d-azur-latest.osm.pbf"
filtered_path = "data/processed/osm/marseille_latest_filtered.osm.pbf"
tag_filter = false

[analyse_network]  # configuration for the analyse_network stage
departure_year = 2023
departure_month = 10
departure_day = 24  # this is the date, not the day of the week
departure_hour = 8
departure_minute = 0
departure_time_window = 1  # this is in hours
max_time = 45  # this is in minutes
write_outputs = true
outputs_dir = "outputs/e2e/marseille/analyse_network/"
qa_travel_times = false  # set to true to qa results with `qa_path`
qa_path = "outputs/e2e/marseille/analyse_network/travel_times.pkl"
save_travel_times_for_qa = true  # set to true to write to `save_qa_path`
save_qa_path = "outputs/e2e/marseille/analyse_network/travel_times.pkl"

[metrics]  # configuration for the metrics stage
cut_off_time = 45   # this is in minutes
cut_off_distance = 11250  # this is in meters
write_outputs = true
outputs_dir = "outputs/e2e/marseille/metrics/"
