# Fixing OS version to avoid breaking OS changes during development stage.
# Will open up OS versions before release.

name: "Render docs"

on:
  push:
    branches: [ "dev", "main" ]

env:
  PYTHON_VERSION: "3.9"

jobs:
  build:
    name: Quarto Render
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # SHA for v4.1.7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@9a7ac94420f42ee15fc60ab88d0dca4be1fd5757 # SHA for v5.1.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.[docs]'
    - name: Install java
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # SHA for v4.2.1
      with:
        distribution: 'temurin'
        java-version: '11.0.21'
    - name: Check Java Install
      run: |
        java --version
    - name: Install linux depencies with apt
      run: |
        sudo apt update
        sudo apt install -y libgeos-dev
        sudo apt-get install osmosis
      shell: sh
    - name: Build API reference pages
      run: |
        python -m quartodoc build
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@c1b50d36cf3c22b3dc7e530bd1b36634e824e545 # SHA for v2.1.4
    - name: Render and Publish
      uses: quarto-dev/quarto-actions/publish@c1b50d36cf3c22b3dc7e530bd1b36634e824e545 # SHA for v2.1.4
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
