name: "Render docs"

on: push

env:
  PYTHON_VERSION: "3.9"
  PUSH_BRANCH: "refs/heads/dev"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Sphinx build  # use -W to turn warnings into errors
      run: |
        make -C docs/ html SPHINXOPTS="-W"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      # deploy if it's being pushed only to this branch
      if: github.ref == ${{ env.PUSH_BRANCH }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
        commit_message: ${{ github.event.head_commit.message }}
