name: "Sphinx: Render docs"

on:
  push:
    branches: [ "102-setup-sphinx" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Sphinx build  # use -W to turn warnings into errors
      run: |
        make -C docs/ html SPHINXOPTS="-W"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
        commit_message: ${{ github.event.head_commit.message }}
