# This workflow will install Windows dependencies, run tests and lint with Python 3.9
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package
on:
  push:
    branches: ["109-develop-windows-os-ci"]
jobs:
  build:
    runs-on: "windows-latest"
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Integration Tests
      run: |
          pytest -m runinteg --runinteg --deselect tests/osm/ --deselect tests/population # run only those tests marked runinteg & with no geos or osmosis deps
    - name: pre-commit
      run: |
        pre-commit install
        pre-commit run --all-files
    - name: Test with pytest
      run: |
        pytest --deselect tests/osm/ --deselect tests/population # run only tests with no osmosis or geos dependencies
